# Generated by Django 4.1.7 on 2023-03-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tarea2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea2',
            old_name='Tarea2',
            new_name='Tarea_do',
        ),
    ]
